package TAkhirPBO;

/**
 *
 * @author Fathir Maula. S/222011503/2KS4
 */
public class BridgePanel extends javax.swing.JPanel {

    /**
     * Creates new form BridgePanel
     */
    public BridgePanel() {
        initComponents();
        spadeTextArea.setEnabled(false);
        heartTextArea.setEnabled(false);
        diamondTextArea.setEnabled(false);
        clubTextArea.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spadeTextField = new javax.swing.JTextField();
        heartTextField = new javax.swing.JTextField();
        diamondTextField = new javax.swing.JTextField();
        clubTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        spadeTextArea = new javax.swing.JTextArea();
        spadeButton = new javax.swing.JButton();
        heartButton = new javax.swing.JButton();
        diamondButton = new javax.swing.JButton();
        clubButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clubTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        diamondTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        heartTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("<html>&nbsp &nbsp &nbsp Olahraga bridge adalah merupakan salah satu bentuk olahraga permainan yang mempergunakan kartu serta menggunakan strategi dan taktik yang istimewa dalam memainkannya.  Selain catur,  bridge merupakan olahraga yang menggunakan dan mengandalkan kecerdasan pikiran para pemainnya.  Tidak banyak olah tubuh digunakan dalam olahraga yang satu ini,  namun olahraga bridge memiliki banyak manfaat terutama dalam ketajaman berpikir");
        jLabel2.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAkhirPBO/image/klim-musalimov-jg5oKe_dz0E-unsplash.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Very quick-short-simple quiz/game hehehehe");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAkhirPBO/image/spade.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAkhirPBO/image/heart.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAkhirPBO/image/Wajik.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAkhirPBO/image/clover.png"))); // NOI18N

        jLabel9.setText("Tebak Nama Suit Card dibawah :p ?!");

        diamondTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diamondTextFieldActionPerformed(evt);
            }
        });

        clubTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        spadeTextArea.setBackground(new java.awt.Color(255, 255, 255));
        spadeTextArea.setColumns(20);
        spadeTextArea.setRows(5);
        spadeTextArea.setBorder(null);
        jScrollPane1.setViewportView(spadeTextArea);

        spadeButton.setText("cek 1");
        spadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spadeButtonActionPerformed(evt);
            }
        });

        heartButton.setText("cek 2");
        heartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartButtonActionPerformed(evt);
            }
        });

        diamondButton.setText("cek 3");
        diamondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diamondButtonActionPerformed(evt);
            }
        });

        clubButton.setText("cek 4");
        clubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        clubTextArea.setBackground(new java.awt.Color(255, 255, 255));
        clubTextArea.setColumns(20);
        clubTextArea.setRows(5);
        clubTextArea.setBorder(null);
        jScrollPane2.setViewportView(clubTextArea);

        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        diamondTextArea.setBackground(new java.awt.Color(255, 255, 255));
        diamondTextArea.setColumns(20);
        diamondTextArea.setRows(5);
        diamondTextArea.setBorder(null);
        jScrollPane3.setViewportView(diamondTextArea);

        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        heartTextArea.setBackground(new java.awt.Color(255, 255, 255));
        heartTextArea.setColumns(20);
        heartTextArea.setRows(5);
        heartTextArea.setBorder(null);
        jScrollPane4.setViewportView(heartTextArea);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("BRIDGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel9)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clubTextField)
                            .addComponent(spadeTextField)
                            .addComponent(heartTextField)
                            .addComponent(diamondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diamondButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clubButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spadeButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(heartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heartButton))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(diamondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diamondButton))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubButton)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jLabel2.getAccessibleContext().setAccessibleName("<html>Olahraga bridge adalah merupakan salah satu bentuk olahraga permainan yang mempergunakan kartu </br> \nserta menggunakan strategi dan taktik yang istimewa dalam memainkannya.  Selain catur, </br>\nbridge merupakan olahraga yang menggunakan dan mengandalkan kecerdasan pikiran para pemainnya.  </br>\nTidak banyak olah tubuh digunakan dalam olahraga yang satu ini, </br>\nnamun olahraga bridge memiliki banyak manfaat terutama dalam ketajaman berpikir </html>");
    }// </editor-fold>//GEN-END:initComponents

    private void diamondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diamondTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_diamondTextFieldActionPerformed
    
    //action untuk mini games
    
    private void heartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartButtonActionPerformed
        // TODO add your handling code here:
        String a = heartTextField.getText();
        if(a.matches("(?i)heart") || a.matches("(?i)Hati") || a.matches("(?i)love")){
        heartTextArea.setText("mudah kan yak, tapi gk semudah \n nebak hati si dia hehehe");
    }else{
            heartTextArea.setText("salah heehhehehehe");
        }
    }//GEN-LAST:event_heartButtonActionPerformed

    private void spadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spadeButtonActionPerformed
        // TODO add your handling code here:
        String a = spadeTextField.getText();
        if(a.matches("(?i)spade") || a.matches("(?i)sekop") || a.matches("(?i)waru") || a.matches("(?i)scope")){
        spadeTextArea.setText("benarrr, tau gak sih kenapa kartu \nsekop warnanya item??? \nkarna kalau merah \nnamanya sekopteng hehe");
    }else{
            spadeTextArea.setText("coba lagi :ppppppp");
        }
    }//GEN-LAST:event_spadeButtonActionPerformed

    private void diamondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diamondButtonActionPerformed
        // TODO add your handling code here:
        String a = diamondTextField.getText();
        if(a.matches("(?i)diamond") || a.matches("(?i)wajik") || a.matches("(?i)berlian")){
        diamondTextArea.setText("selamattt, anda tidak menjawab \n ketupat :v");
    }else{
            diamondTextArea.setText("coba lagi :ppppppp");
        }
    }//GEN-LAST:event_diamondButtonActionPerformed

    private void clubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubButtonActionPerformed
        // TODO add your handling code here:
        String a = clubTextField.getText();
        if(a.matches("(?i)club") || a.matches("(?i)clover") || a.matches("(?i)keriting")){
        clubTextArea.setText("cieee bener, tau gk sih kenapa \nclover ada 3 daunnya :v nyerah ya?? \njawabnnya karna kalau cuma 1\nitu kamu :'");
    }else{
            clubTextArea.setText("maapp ni, anda salah xixixixi");
        }
    }//GEN-LAST:event_clubButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clubTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clubButton;
    private javax.swing.JTextArea clubTextArea;
    private javax.swing.JTextField clubTextField;
    private javax.swing.JButton diamondButton;
    private javax.swing.JTextArea diamondTextArea;
    private javax.swing.JTextField diamondTextField;
    private javax.swing.JButton heartButton;
    private javax.swing.JTextArea heartTextArea;
    private javax.swing.JTextField heartTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton spadeButton;
    private javax.swing.JTextArea spadeTextArea;
    private javax.swing.JTextField spadeTextField;
    // End of variables declaration//GEN-END:variables
}
